### ISSUE TITLE
Debug mode

### ISSUE THREAD

**Issue by JamesonBR** [demyxco/demyx#1]
It would be interesting to have the command to enable debug mode by command line in the development state.

Updating the configuration in wp-config, enabling xdebug in php and restarting to enable it.

**Comment by demyxco** [comment]
Hi thanks for using Demyx, I will add an update after some testing.

**Comment by demyxco** [comment]
Hi @JamesonBR, I've released an update. Try it out now.

**Comment by JamesonBR** [comment]
Great job @demyxco, works like a breeze.

I will analyze and test the code more, so I can contribute as well.

So far, I'm enjoying it.

Thankful!

**Comment by JamesonBR** [comment]
I just felt the need to limit debug only to one instance, could be just for www.domain.xyz/demyx/bs/.

**Comment by demyxco** [comment]
> Great job @demyxco, works like a breeze.

Glad to know!

> To be more secure, it would be interesting to create a UFW or nginx rule to allow access to the development environment for local IP only, not from the server but from the client network.

I've briefly messed with Traefik's allowed IP label but this only works for your actual IP address and not local IP, I'll see what I can do.

**Comment by demyxco** [comment]
Since the first issue/request has been solved, I will be closing this. Feel free to open a new one!
