### ISSUE TITLE
demyx host edit's nano wants to write to /tmp/.demyx but can't

### ISSUE THREAD

**Issue by NuclearMonster** [demyxco/demyx#13]
demyx 1.2.3 
Ubuntu: 20.04

demyx host edit opens nano, with the correct file, but the editor tries to write to /tmp/.demyx and can't

    [ Error writing /tmp/.demyx: Permission denied ]

**Comment by demyxco** [comment]
Weird error! Can you paste the output of `stat ~/.demyx`.

**Comment by NuclearMonster** [comment]
File: /home/[USERNAME]/.demyx
  Size: 816             Blocks: 8          IO Block: 4096   regular file
Device: fc01h/64513d    Inode: 534929      Links: 1
Access: (0664/-rw-rw-r--)  Uid: ( 1003/[USERNAME])   Gid: ( 1003/[USERNAME])
Access: 2020-11-10 01:59:09.954410641 -1000
Modify: 2020-11-10 01:59:09.426417656 -1000
Change: 2020-11-10 01:59:09.426417656 -1000

**Comment by demyxco** [comment]
Thanks for that, I will use a different approach when editing the `~/.demyx` file. For now, you can edit it directly using:

```
nano `~/.demyx`
```

**Comment by demyxco** [comment]
Updated how `~/.demyx` will be edited: https://github.com/demyxco/demyx/commit/2c76e2b0c3965354cd0438008a2dbcdf5b831d24
