### ISSUE TITLE
demyx list fails until a site is set up

### ISSUE THREAD

**Issue by NuclearMonster** [demyxco/demyx#17]
If you run `demyx list` on a fresh install the output should be a very short lists as no sites are set up. Instead, demyx errors out.

Reproduction steps:
1) Install demyx
2) type `demyx list` on the command line

Expected result:
```
+--------+-----------------+
| DEMYX  |  WORDPRESS (0)  |
+--------+-----------------+
|        |                 |
+--------+-----------------+
```

Actual result::
`/etc/demyx/function/list.sh: line 32: cd: /demyx/app/wp: No such file or directory`

**Comment by demyxco** [comment]
It seems like there was no check if wp directory existed; fixed: https://github.com/demyxco/demyx/commit/52995e5148640858762517969a27d4d24e7a9cc2
