### ISSUE TITLE
Demyx Container - iptables error

### ISSUE THREAD

**Issue by JamesonBR** [demyxco/demyx#2]
After the Demyx service is running for a few hours, it usually stops and cannot restart due to IPTables error, even though port 2222 is not in use on the server.

ERROR: for demyx  Cannot start service demyx: driver failed programming external connectivity on endpoint demyx (...):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 2222 -j DNAT --to-destination 172.22.0.2:2222 ! -i br-...: iptables: No chain/target/match by that name.
 (exit status 1))

Any way around this error without having to restart the docker?

**Comment by demyxco** [comment]
Do you ssh into the demyx container at all? If not, try starting up demyx with a different port: `demyx --ssh=1234` and see if the issue persists.

**Comment by JamesonBR** [comment]
Looking at the system debug, I could see that Docker rules in IPTables were being cleared by APF firewall, so it was generating the error:

Dec 17 06:25:01 virtualserver01 apf(30639): {glob} flushing & zeroing chain policies
Dec 17 06:25:01 virtualserver01 apf(30639): {glob} firewall offline
Dec 17 06:25:02 virtualserver01 apf(30674): {glob} activating firewall
Dec 17 06:25:02 virtualserver01 apf(30714): {glob} kernel version not equal to 2.4.x or 2.6.x, aborting.
Dec 17 06:25:02 virtualserver01 apf(30674): {glob} firewall initalized

The solution was to remove apf.
