### ISSUE TITLE
Domain name is not set when installing stack ols-bedrock

### ISSUE THREAD

**Issue by edsonsantoro** [demyxco/demyx#20]
Hi again,

When installing wordpress with `demyx run --stack=ols-bedrock` the domain name is not set on environment variable `WP_HOME` inside `/demyx/.env` file. Right after installing, the var value is `WP_HOME=https://localhost`

**Comment by demyxco** [comment]
Hi @edsonsantoro it seems like you're missing the domain name in that command. I've added a measure to prevent running the command when a domain isn't passed: https://github.com/demyxco/demyx/commit/f067d03adea66e6b5a4ca008b68900bd849ac978
