### ISSUE TITLE
Demyx backp argument --path results in "unknown option: --path"

### ISSUE THREAD

**Issue by olerap** [demyxco/demyx#21]
<img width="434" alt="image" src="https://user-images.githubusercontent.com/32387872/112065142-715f6600-8b64-11eb-9991-7ffa215f580b.png">

I'm currently going through Demyx options and noticed this. Running the latest release. Could you look into this? Thanks for all the work you've done so far!

**Comment by demyxco** [comment]
Hi @olerap you'll need to use = instead of space

```
sudo demyx backup all --path=/somewhere/path
```

**Comment by olerap** [comment]
Ah, it works now. Thanks!
