### ISSUE TITLE
Starting dev mode do not work

### ISSUE THREAD

**Issue by arrkiin** [demyxco/demyx#3]
After trying to start the dev mode with the following command
`$ demyx config <domain> --dev`

The following output is shown but the code-server cannot be accessed
```
Updating configs ... done
/etc/demyx/function/global.sh: line 236: /etc/demyx/function/yml--dev.sh: No such file or directory
Turning off healthcheck ... done
<domain>_wp_dae7e1bb_1 is up-to-date
<domain>_db_dae7e1bb_1 is up-to-date
<domain>_nx_dae7e1bb_1 is up-to-date
+--------------+-----------------------------------------+
| DEMYX        |  DEVELOPMENT                            |
+--------------+-----------------------------------------+
| CODE-SERVER  |  https://<domain>/demyx/cs/             |
| BROWSERSYNC  |  https://<domain>/demyx/bs/             |
| PASSWORD     |  <password>                             |
+--------------+-----------------------------------------+
```
I also updated demyx with
`demyx update && demyx update --system`

**Comment by demyxco** [comment]
Did you refresh the config of your WP app first?

```
demyx config <domain> --refresh
demyx config <domain> --dev
```

**Comment by arrkiin** [comment]
Ok. Did the refresh, but then stepped into the problem with my docker override yml. Because I modified my nginx config and you changed from nginx to openlitespeed, it didn't find the container anymore. So I removed the override and was able to refresh the config. After that the dev flag was working as expected. Thanks.

**Comment by demyxco** [comment]
Glad you got it solved!
