### ISSUE TITLE
[bug] timezone flag does not work

### ISSUE THREAD

**Issue by TheWiresharkGuy** [demyxco/demyx#4]
Hi!

The `--tz` flag seems not working

_maybe I'm not using it correctly_

![image](https://user-images.githubusercontent.com/37513220/83360784-3b0deb80-a384-11ea-8a9a-680b8d57118b.png)

**Thank you** for this incredible project!

**Comment by demyxco** [comment]
Hi @TheWiresharkGuy sorry for the delay. I’ve been working on a new update for demyx with a bunch of new features. Will be releasing sometime this week.

**Comment by TheWiresharkGuy** [comment]
@demyxco Sorry It works I didn't look deep enough `--tz=TIMEZONE` works

**Comment by demyxco** [comment]
Awesome, yeah the next update will have all flags removed from the host and instead demyx will be configurable using a config file in `~/.demyx`.

**Comment by TheWiresharkGuy** [comment]
No problems, It's already awesome ^^

BTW is there an easy way to rename a wordpress app? Like from site.tld to www.site.tld

**Comment by demyxco** [comment]
You can clone the current app via `demyx run www.domain.tld —clone=domain.tld` and then remove the domain.tld via `demyx rm domain.tld`.

**Comment by TheWiresharkGuy** [comment]
> 
> 
> You can clone the current app via `demyx run www.domain.tld —clone=domain.tld` and then remove the domain.tld via `demyx rm domain.tld`.

Thanks It works but the only problem is that even after deleting the first app with `demyx rm domain.tld` the `demyx/traefik` container keeps the old LE certificates from `domain.tld` instead of initiating a challenge for `www.domain.tld`
