### ISSUE TITLE
Traefik dashboard basic auth keeps asking

### ISSUE THREAD

**Issue by galaczi** [demyxco/demyx#8]
This is my first server where I am running demyx so I might be missing something. I have ran the host install a couple times to make sure I have the correct credentials. However, every time after I enter the username and password, the prompt pops up again and I don't get access to the Traefik dashboard.

Any troubleshooting ideas would be much appreciated.

**Comment by demyxco** [comment]
I think it's due to the password being too long. Will have a fix in 1.3.0, so until then try removing a lot of the characters in the generated password.

**Comment by galaczi** [comment]
> 
> 
> I think it's due to the password being too long. Will have a fix in 1.3.0, so until then try removing a lot of the characters in the generated password.

Thanks for your reply! Are you suggesting trial and error to figure out how many characters of the password to use? Or is there a way to change the autogenerated password?

**Comment by demyxco** [comment]
You can directly edit the file that the demyx container uses. Edit `DEMYX_HOST_AUTH_PASSWORD` by using the commands:

```
demyx host edit && demyx host restart
```

In the next release, I will automatically restart the demyx container after `demyx host edit` gets executed.

**Comment by johnkennyuk** [comment]
This issue is still a problem as i clean installed on 12/19/2020 and had the same problem until i found this closed issue and the manual password change resolved the loop, was this issue supposedly fixed??

**Comment by demyxco** [comment]
Hi @johnkennyuk the issue isn't fixed it, sorry. It will be fixed in version `1.3.0`.

**Comment by johnkennyuk** [comment]
Thanks
